<?php
/**
 * Created by PhpStorm.
 * User: Vito
 * Date: 2022/7/7
 * Time: 11:25
 */

namespace app\admin\curd\system_log;

use app\admin\curd\Read;

class SystemLogRead extends Read
{
    use SystemLogTrait;

    //需要展示的字段
    protected $field = [];
    //排除字段
    protected $withoutField = false;
    //追加输出的属性
    protected $append = [];
    //条件
    protected $where = [];

    protected $labelCallback = [
        'get_module_enum' => ['name' => '模块'],
    ];

    protected function readMiddleware($next, $model)
    {
        $this->withUser($model);

        return parent::readMiddleware($next, $model); // TODO: Change the autogenerated stub
    }

}
