<?php
/**
 * Created by Command.
 * User: Vito
 */

namespace app\customer\curd\waterFetcher;

use app\customer\curd\Delete;
use app\exception\DataCannotBeDeletedException;
use think\Model;

class WaterFetcherDelete extends Delete
{
    //排除的数据
    protected $exclude = [];
    //条件
    protected $where = [];

    protected function deleteMiddleware($next, Model $model)
    {
        $response = parent::deleteMiddleware($next, $model); // TODO: Change the autogenerated stub

        if ($response && $model->flow) {
            //吧流量返还给客户
            $user       = $this->user->getUserInfo();
            $user->flow = ['inc', $model->flow];
            $user->save();
        }

        return $response;
    }
}
