<?php
/**
 * Created by Command.
 * User: Vito
 */

namespace app\admin\crud\system_role;

use app\admin\crud\Update;
use app\common\Enum;
use app\exception\MessageException;
use app\validate\SystemRoleValidate;
use think\Model;

class SystemRoleUpdate extends Update
{
    use SystemRoleTrait;

    //验证器
    protected $validate = [
        SystemRoleValidate::class => Enum::VALID_UPDATE_SCENE,
    ];
    //允许新增的数据字段
    protected $field = ['mark', 'auth_ids', 'name'];
    //获取对象时追加的字段
    protected $appendField = [];
    //排除的数据
    protected $exclude = [];
    //条件
    protected $where = [];

    protected function saveMiddleware($next, Model $model, array $params)
    {
        $this->disabledModifySuperAdmin($model);

        if (!$this->hasRoleToDo($model)) {
            throw new MessageException('无权限更新该角色');
        }

        return parent::saveMiddleware($next, $model, $params); // TODO: Change the autogenerated stub
    }
}
