<?php
/**
 * Created by PhpStorm.
 * User: 19248
 * Date: 2022/11/5
 * Time: 22:13
 */

namespace app\admin\curd;

class Edit extends \app\common\curd\Edit
{
    use LangTrait;

    protected $_labelCallback = [];

    protected function _init($next)
    {
        $response = parent::_init($next); // TODO: Change the autogenerated stub

        $this->setLangLabel()->setLangWith();

        return $response;
    }
}
