<?php
/**
 * Created by Command.
 * User: Vito
 */

namespace app\admin\crud\system_auth;

use app\admin\crud\Delete;
use app\exception\MessageException;
use app\admin\crud\system_role\SystemRoleTrait;
use think\Model;

class SystemAuthDelete extends Delete
{
    use SystemRoleTrait;

    //排除的数据
    protected $exclude = [];
    //条件
    protected $where = [];

    protected function deleteMiddleware($next, Model $model)
    {
        $ids = $this->getHasAuthId();

        if (is_array($ids) && !in_array($model->id, $ids)) {
            throw new MessageException('无权限删除');
        }

        return parent::deleteMiddleware($next, $model); // TODO: Change the autogenerated stub
    }
}
