<?php
/**
 * Created by Command.
 * User: Vito
 */

namespace app\admin\curd\system;

use app\common\curd\Update;
use app\exception\MessageException;
use think\Model;

class SystemAuthUpdate extends Update
{
    use CheckSystemRoleTrait;
    //验证器
    protected $validate = [];
    //允许新增的数据字段
    protected $field = [];
    //获取对象时追加的字段
    protected $appendField = [];
    //排除的数据
    protected $exclude = [];
    //条件
    protected $where = [];

    protected function saveMiddleware($next, Model $model, array $params)
    {
        $ids = $this->getHasAuthId();

        if (is_array($ids) && !in_array($model->id, $ids)) {
            throw new MessageException('无权限更新');
        }

        return parent::saveMiddleware($next, $model, $params); // TODO: Change the autogenerated stub
    }
}