<?php
/**
 * Created by Command.
 * User: Vito
 */

namespace app\admin\curd\system;

use app\common\curd\Read;
use app\exception\MessageException;

class SystemRoleRead extends Read
{
    use SystemRoleTrait;

    //需要展示的字段
    protected $field = [];
    //排除字段
    protected $withoutField = false;
    //追加输出的属性
    protected $append = ['auth'];
    //条件
    protected $where = [];

    protected function readMiddleware($next, $model)
    {
        if (!$this->hasRoleToDo($model)) {
            throw new MessageException('无权限获取该角色');
        }

        return parent::readMiddleware($next, $model); // TODO: Change the autogenerated stub
    }
}