<?php
/**
 * Created by Command.
 * User: Vito
 */

namespace app\admin\curd\system;

use app\common\curd\Edit;
use app\common\Util;
use app\exception\MessageException;
use app\logic\SystemAuthLogic;

class SystemRoleEdit extends Edit
{
    use CheckSystemRoleTrait;

    //显示的字段
    protected $field = [];
    //查询条件
    protected $where = [];
    //关联
    protected $with = null;
    //追加字段
    protected $append = ['auth'];
    //追加数据回调
    protected $appendCallback = [];

    protected $labelCallback = [
        'get_auth_label' => ['name' => '权限', 'key' => 'auth'],
    ];

    protected function editMiddleware($next, $model)
    {
        if (!$this->hasRoleToDo($model)) {
            throw new MessageException('无权限获取该角色');
        }

        return parent::editMiddleware($next, $model); // TODO: Change the autogenerated stub
    }

    public function getAuthLabel()
    {
        $logic = new SystemAuthLogic();

        $role = $this->user->getUserInfo()->role;

        $args = [
            'field' => ['id', 'name', 'route', 'pid'],
            'where' => [
                ['module', '=', 'admin'],
            ],
            'scope' => ['status'],
            'limit' => 0,
        ];

        //非超管则只可以设置自己有的权限
        if (!$role->isSuper()) {
            $ids             = $this->user->role->auth_ids;
            $args['where'][] = ['id', 'IN', $ids];
        }

        $list = $logic->getAll($args)->toArray();

        $result = Util::tree($list);

        return $result;
    }
}